email: support@superuser.su
description: >
  Круизные теплоходы компании Мостурфлот.
  Расписание, маршруты, бронирование.
markdown: kramdown
title: Речные круизы
subtitle: Круизы по рекам России
image: /assets/img/slider/slide1.jpg
